In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [3]:
data=pd.read_csv('clean_datas.csv')
data.head()

year  month stateDescription   sectorName  customers  price   revenue       sales
0  2001      1          Wyoming  all sectors        NaN   4.31  48.12840  1116.17208
1  2001      1          Wyoming   commercial        NaN   5.13  12.67978   247.08691
2  2001      1          Wyoming   industrial        NaN   3.26  19.60858   602.30484
3  2001      1          Wyoming        other        NaN   4.75   0.76868    16.17442
4  2001      1          Wyoming  residential        NaN   6.01  15.07136   250.60591

#### Label Encoding

> Ordinal Data


In [4]:
x=data['sectorName']

In [16]:
# pandas way
encoded,rule=x.factorize()

In [17]:
encoded

array([0, 1, 2, ..., 2, 4, 5], shape=(85870,))

In [18]:
rule

Index(['all sectors', 'commercial', 'industrial', 'other', 'residential',
       'transportation'],
      dtype='object')

In [19]:
# sklearn way
lencoder=LabelEncoder()
en=lencoder.fit_transform(x)


In [20]:
en

array([0, 1, 2, ..., 2, 4, 5], shape=(85870,))

In [21]:
lencoder.inverse_transform([0,4,3,5])

array(['all sectors', 'residential', 'other', 'transportation'],
      dtype=object)

#### One-Hot Encoding


> Nomial Data


In [23]:
# pandas way
pd.get_dummies(x,dtype=int)

all sectors  commercial  industrial  other  residential  transportation
0                1           0           0      0            0               0
1                0           1           0      0            0               0
2                0           0           1      0            0               0
3                0           0           0      1            0               0
4                0           0           0      0            1               0
...            ...         ...         ...    ...          ...             ...
85865            1           0           0      0            0               0
85866            0           1           0      0            0               0
85867            0           0           1      0            0               0
85868            0           0           0      0            1               0
85869            0           0           0      0            0               1

[85870 rows x 6 columns]

In [34]:
# sklearn way
one_hot=OneHotEncoder(sparse_output=False)
encoder=one_hot.fit_transform(x.values.reshape(-1,1))

In [35]:
encoder

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], shape=(85870, 6))

In [36]:
one_hot.categories_

[array(['all sectors', 'commercial', 'industrial', 'other', 'residential',
        'transportation'], dtype=object)]